# Generated by Django 3.1.7 on 2021-04-25 20:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('roomnumber', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('beds', models.CharField(default='1', max_length=20)),
                ('bed_size', models.CharField(default='single', max_length=20)),
                ('occupancy', models.IntegerField()),
                ('is_occupied', models.BooleanField(default=False)),
                ('photo_main', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('bathroom', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('tv', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_1', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('date_in', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('date_out', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('hotel_id', models.ForeignKey(default='1', on_delete=django.db.models.deletion.DO_NOTHING, to='hotels.hotel')),
            ],
        ),
    ]
