# Generated by Django 3.1.7 on 2021-04-09 06:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('roomnumber', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('price', models.IntegerField()),
                ('beds', models.IntegerField()),
                ('occupancy', models.IntegerField()),
                ('is_occupied', models.BooleanField(default=True)),
                ('photo_main', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('bathroom', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('tv', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_1', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('date_in', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('date_out', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='hotel_address', to='hotels.hotel')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='hotel_city', to='hotels.hotel')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='hotel_state', to='hotels.hotel')),
                ('zipcode', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='hotel_zipcode', to='hotels.hotel')),
            ],
        ),
    ]
