# Generated by Django 3.1.7 on 2021-04-25 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_auto_20210419_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='is_occupied',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='listing',
            name='roomnumber',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='listing',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
