# Generated by Django 3.1.7 on 2021-04-20 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0001_initial'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='jobtitle',
            new_name='fname',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='staff_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='level',
            new_name='lname',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='name',
            new_name='security_level',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='payrate',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='paytype',
        ),
        migrations.AlterField(
            model_name='staff',
            name='job_description',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='position.position'),
        ),
    ]
