# Generated by Django 3.1.7 on 2021-05-01 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0002_auto_20210426_0221'),
        ('staff', '0004_auto_20210426_0221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='job_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='position.position'),
        ),
    ]
