# Generated by Django 3.1.7 on 2021-04-26 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_auto_20210426_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='photo_main',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
